# Generated by Django 2.2.16 on 2020-10-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misCarWash', '0002_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('nombre', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
